name:                words
version:             0.1.0.0
github:              "shreykumar/words"
license:             BSD3
author:              "Shreyansh Kumar"
maintainer:          "shreykumar961@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shreykumar/words#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random

library:
  source-dirs: src

executables:
  words:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - words
    - random

tests:
  words-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - words
    - hspec
